package project.banana;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Yanis (member 2)
 */
public class GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());
   
    private java.util.List<HealthProfessional> healthProfessionalList = new java.util.ArrayList<>();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        updateProfessionalsComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        taskListTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        professionalsTable = new javax.swing.JTable();
        tab1BUTTONS = new javax.swing.JPanel();
        addProfessional = new javax.swing.JButton();
        editProfessional = new javax.swing.JButton();
        removeProfessional = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        professionalsList = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        diaryTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        addAppointment = new javax.swing.JButton();
        editAppointment = new javax.swing.JButton();
        deleteAppointment = new javax.swing.JButton();
        refreshPageTAB2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        startDate = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        endDate = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        sessionDuration = new javax.swing.JSpinner();
        searchAvailableSlots = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        slotsPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        professionalsList2 = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel15 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tasksTable = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        addTask = new javax.swing.JButton();
        editTask = new javax.swing.JButton();
        deleteTask = new javax.swing.JButton();
        checkButton = new javax.swing.JButton();
        mainHeader = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        undoButton = new javax.swing.JButton();
        redoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("App");
        setBackground(new java.awt.Color(249, 255, 255));
        setName("Main Page"); // NOI18N
        setSize(new java.awt.Dimension(600, 600));

        taskListTab.setBackground(new java.awt.Color(0, 153, 153));
        taskListTab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        taskListTab.setForeground(new java.awt.Color(255, 255, 255));
        taskListTab.setToolTipText("");
        taskListTab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        taskListTab.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        taskListTab.setName("Professionals"); // NOI18N
        taskListTab.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(249, 255, 255));

        professionalsTable.setBackground(new java.awt.Color(237, 250, 250));
        professionalsTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        professionalsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Profession", "Location"
            }
        ){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
    );
    jScrollPane1.setViewportView(professionalsTable);

    jScrollPane2.setViewportView(jScrollPane1);

    tab1BUTTONS.setBackground(new java.awt.Color(249, 255, 255));

    addProfessional.setBackground(new java.awt.Color(153, 255, 204));
    addProfessional.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
    addProfessional.setForeground(new java.awt.Color(0, 102, 102));
    addProfessional.setText("Add");
    addProfessional.addActionListener(this::addProfessionalActionPerformed);
    tab1BUTTONS.add(addProfessional);

    editProfessional.setBackground(new java.awt.Color(153, 255, 204));
    editProfessional.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
    editProfessional.setForeground(new java.awt.Color(0, 102, 102));
    editProfessional.setText("Edit");
    editProfessional.addActionListener(this::editProfessionalActionPerformed);
    tab1BUTTONS.add(editProfessional);

    removeProfessional.setBackground(new java.awt.Color(153, 255, 204));
    removeProfessional.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
    removeProfessional.setForeground(new java.awt.Color(0, 102, 102));
    removeProfessional.setText("Remove");
    removeProfessional.addActionListener(this::removeProfessionalActionPerformed);
    tab1BUTTONS.add(removeProfessional);

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 100, Short.MAX_VALUE)
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 100, Short.MAX_VALUE)
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                .addComponent(tab1BUTTONS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(80, 80, 80))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(tab1BUTTONS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    taskListTab.addTab("Professionals", jPanel1);

    jPanel2.setBackground(new java.awt.Color(249, 255, 255));

    jPanel6.setBackground(new java.awt.Color(249, 255, 255));
    jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setText("Professional:");
    jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

    professionalsList.addActionListener(this::professionalsListActionPerformed);
    jPanel6.add(professionalsList, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, 30));

    jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(102, 102, 102));
    jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel2.setText("searching.. 1ms");
    jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 10, -1, -1));

    diaryTable.setBackground(new java.awt.Color(237, 250, 250));
    diaryTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    diaryTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
        },
        new String [] {
            "Date", "Treatment", "ID", "Start", "End", "Co-workers", "Patient"
        }
    ){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    }
    );
    jScrollPane3.setViewportView(diaryTable);

    jPanel7.setBackground(new java.awt.Color(249, 255, 255));

    addAppointment.setBackground(new java.awt.Color(153, 255, 204));
    addAppointment.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    addAppointment.setForeground(new java.awt.Color(0, 102, 102));
    addAppointment.setText("Add Apointment");
    addAppointment.addActionListener(this::addAppointmentActionPerformed);
    jPanel7.add(addAppointment);

    editAppointment.setBackground(new java.awt.Color(153, 255, 204));
    editAppointment.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    editAppointment.setForeground(new java.awt.Color(0, 102, 102));
    editAppointment.setText("Edit");
    editAppointment.addActionListener(this::editAppointmentActionPerformed);
    jPanel7.add(editAppointment);

    deleteAppointment.setBackground(new java.awt.Color(153, 255, 204));
    deleteAppointment.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    deleteAppointment.setForeground(new java.awt.Color(0, 102, 102));
    deleteAppointment.setText("Delete");
    deleteAppointment.addActionListener(this::deleteAppointmentActionPerformed);
    jPanel7.add(deleteAppointment);

    refreshPageTAB2.setBackground(new java.awt.Color(255, 255, 153));
    refreshPageTAB2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    refreshPageTAB2.setForeground(new java.awt.Color(0, 102, 102));
    refreshPageTAB2.setText("Refresh");
    refreshPageTAB2.addActionListener(this::refreshPageTAB2ActionPerformed);
    jPanel7.add(refreshPageTAB2);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(196, Short.MAX_VALUE))
    );

    taskListTab.addTab("Diary", jPanel2);

    jPanel3.setBackground(new java.awt.Color(249, 255, 255));

    jPanel8.setBackground(new java.awt.Color(249, 255, 255));

    jLabel3.setText("Select professional:");

    jLabel6.setText("Date From:");

    jPanel10.setBackground(new java.awt.Color(237, 250, 250));
    jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

    buttonGroup1.add(jRadioButton1);
    jRadioButton1.setText("Banana");
    jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);
    jPanel10.add(jRadioButton1);

    buttonGroup1.add(jRadioButton2);
    jRadioButton2.setText("Chhese");
    jPanel10.add(jRadioButton2);

    buttonGroup1.add(jRadioButton3);
    jRadioButton3.setText("No");
    jPanel10.add(jRadioButton3);

    buttonGroup1.add(jRadioButton4);
    jRadioButton4.setText("Wird");
    jPanel10.add(jRadioButton4);

    jScrollPane4.setViewportView(jPanel10);

    startDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), new java.util.Date(1798761600000L), java.util.Calendar.DAY_OF_MONTH));

    jLabel4.setText("Date to:");

    endDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), new java.util.Date(1798761600000L), java.util.Calendar.DAY_OF_MONTH));

    jLabel7.setText("Minimum Duration (mins):");

    sessionDuration.setModel(new javax.swing.SpinnerNumberModel(1, 1, 300, 1));

    searchAvailableSlots.setBackground(new java.awt.Color(153, 255, 204));
    searchAvailableSlots.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    searchAvailableSlots.setForeground(new java.awt.Color(0, 102, 102));
    searchAvailableSlots.setText("Find Available Slots");
    searchAvailableSlots.addActionListener(this::searchAvailableSlotsActionPerformed);

    javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
    jPanel8.setLayout(jPanel8Layout);
    jPanel8Layout.setHorizontalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel8Layout.createSequentialGroup()
            .addGap(49, 49, 49)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(searchAvailableSlots)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sessionDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
            .addContainerGap(50, Short.MAX_VALUE))
    );
    jPanel8Layout.setVerticalGroup(
        jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel8Layout.createSequentialGroup()
            .addGap(38, 38, 38)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(24, 24, 24)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(sessionDuration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(29, 29, 29)
            .addComponent(searchAvailableSlots)
            .addGap(19, 19, 19))
    );

    jPanel9.setBackground(new java.awt.Color(237, 250, 250));
    jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Results:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Ubuntu Mono", 0, 12))); // NOI18N

    slotsPanel.setBackground(new java.awt.Color(230, 250, 250));
    slotsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    slotsPanel.setLayout(new javax.swing.BoxLayout(slotsPanel, javax.swing.BoxLayout.Y_AXIS));

    jLabel8.setText("monday session");
    slotsPanel.add(jLabel8);

    jLabel9.setText("banana");
    slotsPanel.add(jLabel9);

    jLabel10.setText("monda2 siosn");
    slotsPanel.add(jLabel10);

    jLabel11.setText("hu");
    slotsPanel.add(jLabel11);

    jLabel12.setText("happiness and sad");
    slotsPanel.add(jLabel12);

    jScrollPane5.setViewportView(slotsPanel);

    javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
    jPanel9.setLayout(jPanel9Layout);
    jPanel9Layout.setHorizontalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanel9Layout.setVerticalGroup(
        jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel9Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane5)
            .addContainerGap())
    );

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );
    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );

    taskListTab.addTab("Search", jPanel3);

    jPanel4.setBackground(new java.awt.Color(249, 255, 255));

    jPanel12.setBackground(new java.awt.Color(249, 255, 255));

    jLabel13.setText("Professional:");

    professionalsList2.setModel(professionalsList.getModel());
    professionalsList2.addActionListener(this::professionalsList2ActionPerformed);

    javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
    jPanel12.setLayout(jPanel12Layout);
    jPanel12Layout.setHorizontalGroup(
        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel12Layout.createSequentialGroup()
            .addGap(35, 35, 35)
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(professionalsList2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel12Layout.setVerticalGroup(
        jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel12Layout.createSequentialGroup()
            .addGap(13, 13, 13)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13)
                .addComponent(professionalsList2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(15, Short.MAX_VALUE))
    );

    jPanel13.setBackground(new java.awt.Color(249, 255, 255));

    jPanel15.setBackground(new java.awt.Color(249, 255, 255));
    jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tasks:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));
    jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.Y_AXIS));

    tasksTable.setBackground(new java.awt.Color(237, 250, 250));
    tasksTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    tasksTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "ID", "Priority", "Description                             ", "Done"
        }
    ){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    }
    );
    jScrollPane7.setViewportView(tasksTable);

    jPanel15.add(jScrollPane7);

    jScrollPane6.setViewportView(jPanel15);

    javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
    jPanel13.setLayout(jPanel13Layout);
    jPanel13Layout.setHorizontalGroup(
        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel13Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
            .addContainerGap())
    );
    jPanel13Layout.setVerticalGroup(
        jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel13Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
            .addContainerGap())
    );

    jPanel14.setBackground(new java.awt.Color(249, 255, 255));

    addTask.setBackground(new java.awt.Color(153, 255, 204));
    addTask.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    addTask.setForeground(new java.awt.Color(0, 102, 102));
    addTask.setText("Add Task");
    jPanel14.add(addTask);

    editTask.setBackground(new java.awt.Color(153, 255, 204));
    editTask.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    editTask.setForeground(new java.awt.Color(0, 102, 102));
    editTask.setText("Edit");
    jPanel14.add(editTask);

    deleteTask.setBackground(new java.awt.Color(153, 255, 204));
    deleteTask.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    deleteTask.setForeground(new java.awt.Color(0, 102, 102));
    deleteTask.setText("Delete");
    jPanel14.add(deleteTask);

    checkButton.setBackground(new java.awt.Color(255, 255, 153));
    checkButton.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
    checkButton.setForeground(new java.awt.Color(0, 102, 102));
    checkButton.setText("Check Done");
    jPanel14.add(checkButton);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(96, Short.MAX_VALUE))
    );

    taskListTab.addTab("Task List", jPanel4);

    mainHeader.setBackground(new java.awt.Color(0, 102, 102));
    mainHeader.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
    mainHeader.setForeground(new java.awt.Color(204, 255, 255));
    mainHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    mainHeader.setText("Health Operator Scheduler");
    mainHeader.setToolTipText("Group Sigma's Project");
    mainHeader.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    mainHeader.setOpaque(true);

    undoButton.setBackground(new java.awt.Color(255, 255, 153));
    undoButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
    undoButton.setText("Undo");
    undoButton.addActionListener(this::undoButtonActionPerformed);

    redoButton.setBackground(new java.awt.Color(255, 255, 102));
    redoButton.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
    redoButton.setText("Redo");
    redoButton.addActionListener(this::redoButtonActionPerformed);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(taskListTab, javax.swing.GroupLayout.Alignment.TRAILING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainHeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(undoButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(redoButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(mainHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(undoButton)
                .addComponent(redoButton))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(taskListTab))
    );

    taskListTab.getAccessibleContext().setAccessibleName("Professionals");

    pack();
    }// </editor-fold>                        

    private void addProfessionalActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // 1. Create the text fields
            javax.swing.JTextField nameField = new javax.swing.JTextField(15);
            javax.swing.JTextField profField = new javax.swing.JTextField(15);
            javax.swing.JTextField locField = new javax.swing.JTextField(15);

            // 2. Create a panel to hold the labels and fields
            javax.swing.JPanel inputPanel = new javax.swing.JPanel();
            inputPanel.setLayout(new java.awt.GridLayout(3, 2, 5, 5));
            inputPanel.add(new javax.swing.JLabel("Name:"));
            inputPanel.add(nameField);
            inputPanel.add(new javax.swing.JLabel("Profession:"));
            inputPanel.add(profField);
            inputPanel.add(new javax.swing.JLabel("Location:"));
            inputPanel.add(locField);

            // 3. Show the window
            int result = javax.swing.JOptionPane.showConfirmDialog(this, inputPanel, 
                    "Add New Health Professional", javax.swing.JOptionPane.OK_CANCEL_OPTION);

            if (result == javax.swing.JOptionPane.OK_OPTION) {
                String baseName = nameField.getText().trim();
                String prof = profField.getText().trim();
                String loc = locField.getText().trim();

                // 4. Validation: No empty fields allowed
                if (baseName.isEmpty() || prof.isEmpty() || loc.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(this, "All fields are required!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // --- UNIQUE NAME LOGIC ---
                String finalName = baseName;
                int count = 0;
                for (HealthProfessional hp : healthProfessionalList) {
                    // Check for exact match or if it already has a version tag like "Name (1)"
                    if (hp.getName().equals(baseName) || hp.getName().startsWith(baseName + " (")) {
                        count++;
                    }
                }
                if (count > 0) {
                    finalName = baseName + " (" + count + ")";
                }
                // -----------------------------

                // 5. Create object using Member 1's class and placeholder ID
                String generatedId = generateNextId();
                HealthProfessional newHP = new HealthProfessional(finalName, generatedId, prof, loc);

                healthProfessionalList.add(newHP);

                // 6. Update Table and ComboBox using the finalName
                DefaultTableModel model = (DefaultTableModel) professionalsTable.getModel();
                model.addRow(new Object[]{generatedId, finalName, prof, loc});
                updateProfessionalsComboBox();
            }
    }                                               

    /**
    * Placeholder for Member 1's ID logic. 
    * Currently just generates a random 3-digit number.
    * keyword: POTATO
    */
   private String generateNextId() {
       // Member 1 should replace this with their TreeMap/Sequential logic
       return "HP-" + (int)(Math.random() * 900 + 100);
   }
    
    
    
    private void professionalsListActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        int index = professionalsList.getSelectedIndex();
        if (index == -1) return;

        // Use Member 1's HealthProfessional class
        HealthProfessional selected = healthProfessionalList.get(index);

        DefaultTableModel model = (DefaultTableModel) diaryTable.getModel();
        model.setRowCount(0);

        // Use Member 1's specific method: getAllAppointments()
        for (Appointment appt : selected.getDiary().getAllAppointments()) {
            model.addRow(new Object[]{
                appt.getStartTime(), 
                appt.getTreatmentType(), 
                "Appt-" + appt.hashCode(), 
                appt.getStartTime(),
                appt.getEndTime(),
                "N/A", 
                "Patient Name"
            });
        }
    }                                                 

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void searchAvailableSlotsActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
    }                                                    

    private void professionalsList2ActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        // TODO add your handling code here:
    }                                                  

    private void removeProfessionalActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        int selectedRow = professionalsTable.getSelectedRow();
        if (selectedRow >= 0) {
            // NOTE FOR MEMBER 1: removedHP is a variable that saves the HP before deletion, useful for the undo LOGIC! 
            // keyword: POTATO
            HealthProfessional removedHP = healthProfessionalList.get(selectedRow);
            
            // NOTE TO MEMBER 1: use the name saveForUndo to write the undo logic
            // keyword: POTATO
            // make sure to uncomment the line below:
            
            // saveForUndo(removedHP, "DELETE"); 
            
            

            // 1. Remove from backend list
            healthProfessionalList.remove(selectedRow);

            // 2. Remove from GUI table
            ((javax.swing.table.DefaultTableModel) professionalsTable.getModel()).removeRow(selectedRow);

            // 3. Refresh dropdowns
            updateProfessionalsComboBox();
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a professional to remove.");
        }
    }                                                  

    private void editProfessionalActionPerformed(java.awt.event.ActionEvent evt) {                                                 
                                          
        int selectedRow = professionalsTable.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a professional to edit.");
            return;
        }

        // 1. Get current data from the list
        HealthProfessional hp = healthProfessionalList.get(selectedRow);

        // 2. Create fields and PRE-FILL them
        javax.swing.JTextField nameField = new javax.swing.JTextField(hp.getName(), 15);
        javax.swing.JTextField profField = new javax.swing.JTextField(hp.getProfession(), 15);
        javax.swing.JTextField locField = new javax.swing.JTextField(hp.getWorkLocation(), 15);

        javax.swing.JPanel editPanel = new javax.swing.JPanel();
        editPanel.setLayout(new java.awt.GridLayout(3, 2, 5, 5));
        editPanel.add(new javax.swing.JLabel("Name:"));
        editPanel.add(nameField);
        editPanel.add(new javax.swing.JLabel("Profession:"));
        editPanel.add(profField);
        editPanel.add(new javax.swing.JLabel("Location:"));
        editPanel.add(locField);

        // 3. Show the window
        int result = javax.swing.JOptionPane.showConfirmDialog(this, editPanel, 
                "Edit Health Professional (ID: " + hp.getId() + ")", javax.swing.JOptionPane.OK_CANCEL_OPTION);

        if (result == javax.swing.JOptionPane.OK_OPTION) {
            String newName = nameField.getText().trim();
            String newProf = profField.getText().trim();
            String newLoc = locField.getText().trim();

            if (!newName.isEmpty() && !newProf.isEmpty() && !newLoc.isEmpty()) {
                
                // NOTE FOR MEMBER 1: Include setter methods in HealthProfessional Class in order to update the list properly.
                // keyword: POTATO
                // make sure to uncomment the lines below:
                
                /**
                hp.setName(newName); 
                hp.setProfession(newProf);
                hp.setWorkLocation(newLoc);
                */

                // 5. Update the GUI Table
                professionalsTable.setValueAt(newName, selectedRow, 1);
                professionalsTable.setValueAt(newProf, selectedRow, 2);
                professionalsTable.setValueAt(newLoc, selectedRow, 3);

                // 6. Sync the ComboBox in Tab 2
                updateProfessionalsComboBox();
            }
        }
    }                                                

    private void addAppointmentActionPerformed(java.awt.event.ActionEvent evt) {                                               
      // USE BACKEND LOGIC FOR ADDING APPOINTMENT HERE
    }                                              

    private void editAppointmentActionPerformed(java.awt.event.ActionEvent evt) {                                                
      // USE BACKEND LOGIC FOR EDITTING APPOINTMENT HERE
    }                                               

    private void deleteAppointmentActionPerformed(java.awt.event.ActionEvent evt) {                                                  
       // USE BACKEND LOGIC FOR REMOVING APPOINTMENT HERE
    }                                                 

    private void refreshPageTAB2ActionPerformed(java.awt.event.ActionEvent evt) {                                                
       // USE BACKEND LOGIC FOR REFRESHING APPOINTMENTS PAGE HERE
    }                                               

    private void redoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          
    
    
    private void updateProfessionalsComboBox() {
        javax.swing.DefaultComboBoxModel<String> comboModel = new javax.swing.DefaultComboBoxModel<>();

        for (HealthProfessional p : healthProfessionalList) {
            comboModel.addElement(p.getName());  // add each name from the list
        }

        professionalsList.setModel(comboModel); // set the new model
    }
    
    
    
  
    /**
    * HANDOVER NOTES FOR TEAM (Member 1, 3, 4):
    * * 1. MAIN METHOD:
    * - The main method below is auto-generated by NetBeans for thread safety (EventQueue.invokeLater).
    * - It also sets the 'Nimbus' Look & Feel so the GUI doesn't look like a 90s app.
    * - If we create a separate 'Driver' class to run the whole project, we can call 
    * 'new GUI().setVisible(true);' from there, but keep this main for local testing.
    */
      /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addAppointment;
    private javax.swing.JButton addProfessional;
    private javax.swing.JButton addTask;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton checkButton;
    private javax.swing.JButton deleteAppointment;
    private javax.swing.JButton deleteTask;
    private javax.swing.JTable diaryTable;
    private javax.swing.JButton editAppointment;
    private javax.swing.JButton editProfessional;
    private javax.swing.JButton editTask;
    private javax.swing.JSpinner endDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel mainHeader;
    private javax.swing.JComboBox<String> professionalsList;
    private javax.swing.JComboBox<String> professionalsList2;
    private javax.swing.JTable professionalsTable;
    private javax.swing.JButton redoButton;
    private javax.swing.JButton refreshPageTAB2;
    private javax.swing.JButton removeProfessional;
    private javax.swing.JButton searchAvailableSlots;
    private javax.swing.JSpinner sessionDuration;
    private javax.swing.JPanel slotsPanel;
    private javax.swing.JSpinner startDate;
    private javax.swing.JPanel tab1BUTTONS;
    private javax.swing.JTabbedPane taskListTab;
    private javax.swing.JTable tasksTable;
    private javax.swing.JButton undoButton;
    // End of variables declaration                   
}


